
name: Release
on:
  push:
    branches:
      - "main"


jobs:

  build:
    name: Build
    runs-on: self-hosted
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: 46.101.148.197
        username: root
        script: whoami

  checkout:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

  build-release:
    runs-on: self-hosted
    steps:
        - name: pull branch
          run: git pull origin master
        - name: restart nginx
          run: sudo service nginx reload
        - name: restart systemd
          run: sudo systemctl restart nginx





